server.port=8080
spring.application.name=climalert-service
spring.threads.virtual.enabled=true

/
weatherapi.base-url=https://api.weatherapi.com/v1
weatherapi.key=6c7a32586f6c48e194b231809260707
weatherapi.location=Buenos Aires,Argentina


spring.datasource.url=jdbc:h2:file:./data/climalert;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=danabejarano7@gmail.com
spring.mail.password=rkbjhtulkibrfrda
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
